### PR TITLE
Add redirect message

### PR DESCRIPTION
**Pull request by UuuNyaa**
Migrating documents
----------------------------

| Status | From | To |
|:--:|:--|:--|
| Done     | [README.md](https://github.com/powroupi/blender_mmd_tools/blob/dev_test/README.md) | [README.md](https://github.com/UuuNyaa/blender_mmd_tools/blob/main/README.md) |
| **Removal** | [README_ja_outdated.md](https://github.com/powroupi/blender_mmd_tools/blob/dev_test/README_ja_outdated.md) |  |
| Done     | [CHANGELOG.md](https://github.com/powroupi/blender_mmd_tools/blob/dev_test/CHANGELOG.md) | [CHANGELOG.md](https://github.com/UuuNyaa/blender_mmd_tools/blob/main/CHANGELOG.md) |
| Done     | [CONTRIBUTORS.md](https://github.com/powroupi/blender_mmd_tools/blob/dev_test/CONTRIBUTORS.md) | [CONTRIBUTORS.md](https://github.com/UuuNyaa/blender_mmd_tools/blob/main/CONTRIBUTORS.md) |
| Done     | [LICENSE](https://github.com/powroupi/blender_mmd_tools/blob/dev_test/LICENSE) | [LICENSE](https://github.com/UuuNyaa/blender_mmd_tools/blob/main/LICENSE) |
| Done     | [Home](https://github.com/powroupi/blender_mmd_tools/wiki) | [Home](https://mmd-blender.fandom.com/wiki/Home) |
| Done     | [1 MMD unit in real world units](https://github.com/powroupi/blender_mmd_tools/wiki/1-MMD-unit-in-real-world-units) | [Unit system](https://mmd-blender.fandom.com/wiki/Unit_system) |
| Done     | [Documentation](https://github.com/powroupi/blender_mmd_tools/wiki/Documentation) | [MMD Tools/Manual](https://mmd-blender.fandom.com/wiki/MMD_Tools/Manual) |
| Done     | [Documentation.ja](https://github.com/powroupi/blender_mmd_tools/wiki/Documentation.ja) | [MMD Tools/マニュアル](https://mmd-blender.fandom.com/ja/wiki/MMD_Tools/%E3%83%9E%E3%83%8B%E3%83%A5%E3%82%A2%E3%83%AB) |
| **ToDo** | [Guide to the mmd_tools Interface](https://github.com/powroupi/blender_mmd_tools/wiki/Guide-to-the-mmd_tools-Interface) | [MMD Tools/UI](https://mmd-blender.fandom.com/ja/wiki/MMD_Tools/UI) |
| Done     | [How to create and edit Material morphs, Group morphs, Bone morphs, UV morphs](https://github.com/powroupi/blender_mmd_tools/wiki/How-to-create-and-edit-Material-morphs,-Group-morphs,-Bone-morphs,-UV-morphs) | [How to create and edit morphs](https://mmd-blender.fandom.com/wiki/How_to_create_and_edit_morphs) |
| Done     | [How to install the mmd_tools Blender add on](https://github.com/powroupi/blender_mmd_tools/wiki/How-to-install-the-mmd_tools-Blender-add-on) | [MMD Tools](https://mmd-blender.fandom.com/wiki/MMD_Tools) |
| **Removal** | [interface notes](https://github.com/powroupi/blender_mmd_tools/wiki/interface-notes) | |
| Done     | [Links to mmd_tools Tutorials](https://github.com/powroupi/blender_mmd_tools/wiki/Links-to-mmd_tools-Tutorials) | [Category:MMD Tools](https://mmd-blender.fandom.com/wiki/Category:MMD_Tools)|
| Done     | [Mmd Tools Shared Toon Texture Folder](https://github.com/powroupi/blender_mmd_tools/wiki/Mmd-Tools-Shared-Toon-Texture-Folder) | [MMD_Tools/Manual#Shared_Toon_Texture_Folder](https://mmd-blender.fandom.com/wiki/MMD_Tools/Manual#Shared_Toon_Texture_Folder)|
| **????** | [MMD_TOOLS LIST OF FEATURES AND BRIEF TUTORIAL INFORMATION FOR FEATURES](https://github.com/powroupi/blender_mmd_tools/wiki/MMD_TOOLS-LIST-OF-FEATURES-AND-BRIEF-TUTORIAL-INFORMATION-FOR-FEATURES) | |
| Done     | [PMX error checker quick reference](https://github.com/powroupi/blender_mmd_tools/wiki/PMX-error-checker-quick-reference) | [MMD Tools/PMX error checker quick reference](https://mmd-blender.fandom.com/wiki/MMD_Tools/PMX_error_checker_quick_reference) |
| Done     | [Translations](https://github.com/powroupi/blender_mmd_tools/wiki/Translations) | [How to translate Japanese names#Available_dictionaries](https://mmd-blender.fandom.com/wiki/How_to_translate_Japanese_names#Available_dictionaries) |
| Done     | [Tutorial mmd_tools model translation feature](https://github.com/powroupi/blender_mmd_tools/wiki/Tutorial-mmd_tools-model-translation-feature) | [How to translate Japanese names](https://mmd-blender.fandom.com/wiki/How_to_translate_Japanese_names) |
| **????** | [Tutorial: How to convert a 3D character model to MMD](https://github.com/powroupi/blender_mmd_tools/wiki/Tutorial:-How-to-convert-a-3D-character-model-to-MMD) | |
| **????** | [Tutorial: How to convert BVH to VMD](https://github.com/powroupi/blender_mmd_tools/wiki/Tutorial:-How-to-convert-BVH-to-VMD) | |

????: Should we migrate?

### CODE REVIEW

**Comment by powroupi** [comment]
Thank you for the changes, shall I merge it now?

>????: Should we migrate?

I think you can migrate all documents or make new documents as you like, I actually did not maintain those documents well, most of those documents were made by users/contributors :sweat_smile:. You may ask original creators for rules if you want to migrate them to another place other than GitHub, I think the history of revisions is meaningful for them. :smiley:

**Comment by UuuNyaa** [comment]
Thank you for your comment and advice.

> shall I merge it now?

Sorry to bother you, but please read the comments below.

~~Yes. Please merge it.~~
~~If possible, please do not close #372 .~~


> You may ask original creators for rules if you want to migrate them to another place other than GitHub, I think the history of revisions is meaningful for them.

OK. I'm going to migrate the documents gradually, asking original creators after #372 is merged.

I will edit the documents as follows:
- Do not delete documents to keep revisions
- Write a redirect message at the top of the document

**Comment by nagadomi** [comment]
As for the wiki documents I have written, feel free to use them. Most of them are translations of English documents though.

I understand and respect powroupi's decision, but my personal opinion was that it would be better for powroupi to create a Github Organization for mmd_tools, transfer the repository, and add UuuNyaa as a Collaborators or Admin. This way powroupi can come back in the future and keep the same URL even if the maintainer changes.

**Comment by UuuNyaa** [comment]
@nagadomi Thank you for your comment

I did not know Github Organization.
If I can be a committer without changing the repository or URL, that would be better.

@powroupi 
Can you accept this option?
Of course, you are welcome to migrate it to my repository if it is a burden for you.

**Comment by nagadomi** [comment]
@UuuNyaa 
Actually, I have never managed Github Organization, but the previous link of the transferred repository will be automatically redirected to the new location. 

>If I can be a committer without changing the repository or URL, that would be better.

An easier way is that pouroupi invites UuuNyaa to be a collaborator in this personal repository. I am not sure if this option is acceptable.
[Inviting collaborators to a personal repository](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository)

**Comment by UuuNyaa** [comment]
> An easier way is that pouroupi invites UuuNyaa to be a collaborator in this personal repository. I am not sure if this option is acceptable.

@powroupi @nagadomi 
I'm fine with this option.
However, I need the authority to accept new collaborators into this repository for when I retire.

After the migration to my repository is done, there is a way for me to do the migration to Github Organization by myself.

**Available Options**
1. Just migrate this repository to my repository
2. Migrate this repository to Github Organization by @powroupi 
3. Invite @UuuNyaa to be a collaborator in this repository (@UuuNyaa retirement problem remains?)
4. In addition to 1, migrate my repository to the Github Organization by @UuuNyaa

**Comment by powroupi** [comment]
Well, I think I'll invite you to be collaborators in this repository for now. So, you can migrate this repository to your repository or organization in the future when necessary. Thank you very much. :smile: 

Maybe give you **Triage** or **Write** access? (see [Manage repository settings](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-teams-and-people-with-access-to-your-repository#changing-permissions-for-a-team-or-person)) :thinking:

**Comment by UuuNyaa** [comment]
@powroupi Thank you.
I've accepted the invitation.

> Maybe give you Triage or Write access?

I did not know which authority I needed.

I want to do migrate this repository to [MMD & Blender Github Organization](https://github.com/MMD-Blender) when I get the authority.

I have invited you to be a owner of the organization.
After you accept my invitation, would you transfer the repository to the organization?


https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-user-account

**Comment by nagadomi** [comment]
@UuuNyaa
It is better not to use indie modelers' work for the repository icon without asking permission. (Only original character images distributed by Crypton Future Media are licensed under CC.)
MMD community is very sensitive to licensing/rules issues, so it is better to not include any of their rights.
(This is my personal opinion for repository management, not about your personal activities.)

**Comment by powroupi** [comment]
@UuuNyaa, I think I'll keep this repository here because we don't know whether if there is any problem could be happened while transferring, it should be easier and safer if you just clone it to your organization. And I guess all download URLs would need to change from `https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip` to `https://github.com/[somewhere]/blender_mmd_tools/archive/dev_test.zip` no matter we transfer or clone this repository to somewhere else.:cry:

By the way, I found I don't have the feature to view or choose your role/permissions, but it's okay for now I think. :sunglasses:

**Comment by powroupi** [comment]
@UuuNyaa,
>I have invited you to be a owner of the organization.

Sorry, I've canceled the invitation to MMD & Blender, currently I don't have time to keep maintaining `mmd_tools`. You can take over it if you want. :smile:

**Comment by UuuNyaa** [comment]
@nagadomi 
Thank you for advising me about rights.
I'll replace it with the official model render result later.

@powroupi 
Sorry. I have invited you to transfer the repository, and I didn't intend for you to continue developing.
In order to do repository transfer, you need to have permission to create repositories for the organization.
I also thought that when you transfer a repository, the URL of each one is also transferred.

In any case, I understand your intention to keep this repository.
Please merge this pull request or give me **Write** access to this repository.

**Comment by UuuNyaa** [comment]
@powroupi 
The download URL will change as follows.

The same format as before:
old: `https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip`
new: `https://github.com/UuuNyaa/blender_mmd_tools/archive/main.zip`

Future release format:
old: nothing
new: `https://github.com/UuuNyaa/blender_mmd_tools/releases`

**Comment by powroupi** [comment]
@UuuNyaa , you should be able to merge this PR since I've added you as a collaborator. See [collaborator-access-for-a-repository-owned-by-a-user-account](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-user-account-settings/permission-levels-for-a-user-account-repository#collaborator-access-for-a-repository-owned-by-a-user-account). It would be useless if you can't do any changes to this repository. :confused: 

I think you should be able to access this repository using GitHub web page or APP using your account, another way is that you can pull `git@github.com:powroupi/blender_mmd_tools.git`, do some changes locally, and then push back [using SSH protocal with your ssh key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh), as a collaborator, if I understand it correctly. :worried: 

If you still can't do anything to this repository, I'll merge this PR, remove collaborators, and suspend/stop maintaining this repository as a last resort. Thank you.

**Comment by UuuNyaa** [comment]
@powroupi I can merge this pull request myself.
Thank you!

**Pull request merged**
