### PR TITLE
Add support for automatically setting the bone roll for arm related bones

### PR DESCRIPTION
**Pull request by nagadomi**
_Sorry for the long description, and my poor English :(_

This PR contains the following changes. These are related to each other.
- Support automatically setting the bone roll for arm related bones in PMX Importer
- Add Flip pose operator for mmd_tools
- Add Recalculate bone roll operator for existing imported models

#### Issue
Since the current mmd_tools does not set the bone roll of arm or finger bones, so it is misaligned. It is difficult to rotate fingers, and it is also difficult to use Graph Editor.

62262ccd6ed5539268483fdae82eb8b3

#### Investigation
MMD has the feature to automatically set the bone roll(local axis) for arm related bones. It is pointed out in PMX specification document.

>※PMDでは腕関連のみ子ボーンの方向をX、手前を-Zとする軸でローカルフレームが自動作成される模様。
>In PMD, it seems that the local frame is automatically created for the arm-related bones. The direction to the child bone is X, the direction towards you is -Z.

Also, the same feature can be seen in MMDAI's source code. (`Bone::hasLocalAxes` and `Bone::getLocalAxes`)
https://github.com/hkrn/MMDAI/blob/9ca74bf9f6f979f510f5355d80805f935cc7e610/libvpvl2/src/core/pmd2/Bone.cc#L455-L492
More details are described on the following blog post. (Japanese)
http://ch.nicovideo.jp/mea/blomaga/ar231383

The conditions under which the bone roll is automatically set are as follows.
- If the bone name matches 左腕,左ひじ,左手首,右腕,右ひじ,右手首
- If the bone name includes 親指,人指,中指,薬指,子指

I also investigated PMX plugins which automatically set local axes, some plugins also support semi-standard bones (arm twist bones).

#### Implementation
So I implemented this feature in PMX Impoter, it will change the bone roll but not local axis property.
The bone roll (and local axis) is the same as when importing a MMD model with the proper local axis (It is compatible with existing features).

f88fd9c84fff5e173020bd0d5cc1dd21

#### Issue
The bone roll when importing a MMD model with the local axis set (also set by the above change), it seems not to be Blender friendly, because Blender's `bpy.ops.pose.paste (flipped=True)` does not work properly.

051a18e150653b3279d753a6f41c4430

Also, `bpy.ops.pose.paste(flipped=True)` has a problem of copying `mmd_bone` property to the opposite side #20.

#### Implementation
So I implemented the flip pose operator for mmd_tools, which works properly with any bone roll. The button for the operator will be displayed in 3D View bottom header when Pose Mode and a MMD model's armature is selected.

b1b83e2f6889cc6a5db07011da72f9ba
bc4530ec22467ee909b591bacb1fed17

The operator works as follows.
- When you selected a bone on one side and run, the pose is applied to matching bone on opposite side of X-Axis
- When you selected bones on both side and run, the pose is flipped on X-Axis.
- Of course, this operator does not break `mmd_bone` property

### (3) Recalculate bone roll operator for existing imported models
This is the operator for applying (1) to existing imported MMD models.
Note that if model has f-curve(action), changing the bone roll will break f-curve. So the warning message will be displayed before running.

The button to run the operator is placed under `Change IK Loop Factor` button on MMD Model Information Tab.

Thanks.

### CODE REVIEW

**Comment by powroupi** [comment]
Awesome, thanks your great changes. :+1: 

Minor issue of flip pose:
```python
# maybe lower case names support (?)
# __LR = (('L', 'R'), ('l', 'r'), ('LEFT', 'RIGHT'), ('Left', 'Right'))
```

**Comment by nagadomi** [comment]
It supported `LEFT` and `left`, but not `Left`.
I've fixed it.

Edit: Updated to more correctly implementation

**Comment by nagadomi** [comment]
Sorry, I refactor this code a bit more.

**Comment by nagadomi** [comment]
I've fixed name matching issue and rebased.

**Comment by powroupi** [comment]
Good. :+1: 

I noticed an issue of the axes of thumb (親指), my steps:
1. import default model `初音ミク.pmd`
2. in pose mode, select `親指１.L`, rotate bone local z-axis 90 degrees
3. click [Flip Pose], the pose of `親指１.R` doesn't look as expected.

I think function `update_auto_bone_roll` may set incorrect axes in some cases. (?) :cry: (it is the only bug)

**Comment by nagadomi** [comment]
Thank you for noticing it.
I've changed the calculation formula for axis. Probably this should be fine.

**Comment by powroupi** [comment]
Hmm, it might fix thumb axis, but it breaks axes of arms (rotate arms and Flip Pose, you'll see the issue). I tried to fix it with original method, but I'm not sure if it works in all cases or not: :sweat_smile: 
```python
    @classmethod
    def update_auto_bone_roll(cls, edit_bone):
        loc = edit_bone.matrix.to_translation()
        mmd_x_axis = edit_bone.vector.normalized().xzy
        mmd_y_axis = mmd_x_axis.copy()
        if loc.x > 0: # left arm
            mmd_y_axis.x = -mmd_y_axis.x
            mmd_y_axis.z = -mmd_y_axis.z # <- fix axis issue
        else:
            mmd_y_axis.y = -mmd_y_axis.y
        mmd_z_axis = mmd_x_axis.cross(mmd_y_axis).normalized()
        cls.update_bone_roll(edit_bone, mmd_x_axis, mmd_z_axis)
```

**Comment by nagadomi** [comment]
Hmm, the model I tried seemed to be working but may have caused further bugs :sob:
Edit: I confused Vector and Euler and failed reload addon :(
(I am not yet familiar with 3D space operation, so this may be wrong)Recognition of my first bug was that caused by the global y position of thumb's head and tail are not aligned, mmd_z should be flipped horizontally to right and left.

Your fix is simple and works fine, so I will update to your change :smile:
I think that the case where a problem is likely to occur is when some element of vector is 0. However, this change is intended to be applied to left-right arms of A-stance, so I think probably no problem.

**Comment by nagadomi** [comment]
I will think about this issue.

**Comment by powroupi** [comment]
>I think that the case where a problem is likely to occur is when some element of vector is 0

Okay, I think this PR will be ready to merge once we fix that issue. (especially vertical tip bone [0, 0, 1])

By the way, we don't need to check `mmd_root` attribute, it will be generated automatically once you access it when `mmd_tools` addon is enabled. So you can safely remove the checks of `mmd_root` in FlipPose.poll() and MMDViewHeader.poll(). (~`getattr(context.active_object, 'mmd_root', None) is not None`~) :smile:

**Comment by nagadomi** [comment]
I've updated `update_auto_bone_roll()`, tested it with all sorts of bones direction.
The previous method did not work well with T-stance.
I believe that this method does not have any problems ..

>mmd_root

OK, I will remove it.

**Comment by powroupi** [comment]
Thank you for your excellent work, I've merged it. :smile:

**Comment by nagadomi** [comment]
Thanks a lot. :smile:
I thought whether to add an import option to disable this feature. If you have something worried, add it.

**Comment by powroupi** [comment]
>I thought whether to add an import option to disable this feature.

I don't think it is necessary. It is working well. :smile:
(I can [Set/Clear Bone Roll] to work around it if it is not working good enough)

**Pull request merged**
