### PR TITLE
Add bone symmetry tool

### PR DESCRIPTION
**Pull request by Vwings**
I try to symmetrize bones' position using blender's symmetrize tool but it will also overrides mmd bones' name and id,  and this cause the exported pmx file has duplicate bone names.  this Bone Symmetry Tool will simply mirror transform properties for bones with '.L' or '.R' postfix.

Features:
* Mirror Left bones' position to Right bones with the same basename
* Mirror Right bones' position to Left bones with the same basename

### CODE REVIEW

**Comment by powroupi** [comment]
Sorry, I can't reproduce this issue. In edit mode, [Armature]->[Symmetrize] is working fine, so far tested on Blender 2.82 and 2.7x. :confused: 

And Blender's Symmetrize only affect selected bones, it's better to follow inventions as possible. :smiley:

**Comment by Vwings** [comment]
> Sorry, I can't reproduce this issue. In edit mode, [Armature]->[Symmetrize] is working fine, so far tested on Blender 2.82 and 2.7x. 😕
> 
> And Blender's Symmetrize only affect selected bones, it's better to follow inventions as possible. 😃

If I select left arm's bone and use Symmetrize tool, the mmd bone name is overrided, I can post a screenshot later, and I'm using blender 2.83.

**Comment by Vwings** [comment]
@powroupi Looks like this issue only produce on Blender 2.83, I tried Blender 2.82 and the Symmetrize tool works fine.

Blender 2.83 test result:
1. Before using Armature Symmetrize
pr1
2. After using Armature Symmetrize, 
pr2

**Comment by powroupi** [comment]
I guess users can workaround this issue by using [X-Axis Mirror](https://docs.blender.org/manual/en/latest/animation/armatures/posing/tool_settings.html#x-axis-mirror), it should affect bone's transform data only. Do not use Armature Symmetrize anymore. :cry:

**Comment by powroupi** [comment]
Thanks for reporting this issue. :smile:  (similar to powroupi#20)

**Pull request closed without merging**
