### PR TITLE
Added slider for Vertex morphs in the panel

### PR DESCRIPTION
**Pull request by lordscales91**
Basically I just try to find the corresponding shape key and the draw its value property. There is problem when the mesh is separated. The Shape Key is duplicated and we don't know which is the "correct" one.

### CODE REVIEW

**Comment by powroupi** [comment]
I was thinking about this, i didn't implement it because it seems to be duplicated with [Display Items] panel. But i think it it better to move it to Vertex morphs panel as you did. :smile: 

About your changes, i have some suggestions:
1) Add null check of shape_keys

``` python
    if mesh.data.shape_keys is None:
        continue
```

2) Would it be better to just use active mesh? :thinking:

**Comment by lordscales91** [comment]
> Add null check of shape_keys

Oops! Didn't thought about that. Thanks for your suggestion

> Would it be better to just use active mesh? :thinking:

Well, with this approach, if you select the model armature or any other object inside the mmd_root you can still use the slider and it will work. Unless the mesh had been separated, in which case we can't keep track of the right Shape Key

**Comment by powroupi** [comment]
You should remove line 358, it will cause problem when you want to change active shape key in shape key panel.

``` python
mesh.active_shape_key_index = idx
```

> Unless the mesh had been separated, in which case we can't keep track of the right Shape Key

Why not list them all just like the [Display Items] panel did? :smile: 

``` python
for i in rig.meshes():
    if i.data.shape_keys is not None and item.name in i.data.shape_keys.key_blocks:
        row = col.row(align=True)
        row.label(i.name+':')
        row.prop(i.data.shape_keys.key_blocks[item.name], 'value')
```

**Comment by lordscales91** [comment]
> You should remove line 358, it will cause problem when you want to change active shape key in shape key panel.

Oops again 😃! I forgot that the panel is re-drawn every time a change happen, including when changing the active shape key. I will remove it in the next commit.

> Why not list them all just like the [Display Items] panel did?

Because the name of the ShapeKey will be **exactly the same**. Because shape keys with the same name can exist in different mesh objects. Therefore displaying them all will not be useful and ... Wait! "Like the [Display Items]" ... Oh! It's [true](https://github.com/powroupi/blender_mmd_tools/blob/bf95aa22ffdc037dfb575e914c19989253566f8c/mmd_tools/panels/tool.py#L235-L239)

Maybe we should remove those lines as well. It makes more sense to manipulate the shape keys (also known as vertex morphs) with the Morph Tools Panel.

I will let you choose which approach is better (displaying them all or just the first one or use the active mesh)

**Comment by powroupi** [comment]
I would prefer to use [L235-L239](https://github.com/powroupi/blender_mmd_tools/blob/bf95aa22ffdc037dfb575e914c19989253566f8c/mmd_tools/panels/tool.py#L235-L239), and then remove [L233-L239](https://github.com/powroupi/blender_mmd_tools/blob/bf95aa22ffdc037dfb575e914c19989253566f8c/mmd_tools/panels/tool.py#L233-L239). :smile: 

It is like a hobby issue, i guess there is no perfect way for now. :disappointed:
But both ways will work well in single mesh case. :smile:

**Comment by lordscales91** [comment]
Ok. With my latest commit I commented the lines in the [Display] panel and changed the Morph Tools panel to use the active mesh to find the shape keys as you suggested. That way, if the selected mesh is the right one the slider will work even in a multi-mesh model.

**Comment by powroupi** [comment]
Okay, not bad, i've merged it. Thank you. :smile:

**Comment by nagadomi** [comment]
Is it possible to remove vertex morphs from unrelated object after `separeted by materials` automatically? 
Sometimes, vertex morph(shapekey) effects unrelated object after editing a mesh.

vetexmorph

In this case, the problem is able to fix with removing `まばたき(eye blink)` shapekey from body object.

EDIT: Maybe I edited mesh on eye blink shapekey=1. It is my mistake. But, I think removing unrelated morph is a useful feature.

**Comment by nathanvasil** [comment]
I run into the same issues as nagadomi all of the time.

It believe it has something to do with moving objects in edit mode, then changing their centers, generally by joining them with another material.  Fixing it is usually doable, but irritating.  I've had fewer problems since I started moving entire objects in object mode instead of edit mode (it's easier to move than hude when you have to go to all of the steps of hiding physics objects following unhide).

I would find nagadomi's suggestion useful as well.

**Comment by powroupi** [comment]
> Is it possible to remove vertex morphs from unrelated object after separeted by materials automatically?

Yes, i know we can go through all shape keys to check vertex offset, but it will be inefficient. (there might be a better way, i don't know :thinking: ) Anyway, it's possible. :smile:

**Comment by powroupi** [comment]
Okay, just quick implement it and simple test, works good. :smile: 

Note: The shape keys will not have correct order after joining objects, so we might need another function to reorder shape keys. :)

EDIT: `shape_key_remove()` is supported in blender 2.75 or later, so this feature will not work in blender old versions at the moment (i'll fix it later). :sweat_smile:

**Comment by nagadomi** [comment]
Thanks!

**Comment by nathanvasil** [comment]
Tests out.  Just one question: why the confirmation dialog?  Is there a reason you wouldn't want to clean shape keys?

**Comment by powroupi** [comment]
> why the confirmation dialog?

Well, it is easier for me to test the code and identify issues without modify the code, i'm still finding the root cause of that issue (just fixed one in [this line](https://github.com/powroupi/blender_mmd_tools/blob/7c9aa96e2620bc95e0c05ab2d6ea37359acea7df/mmd_tools/utils.py#L99)).

I can disable it next time. :)

**Pull request merged**
