### PR TITLE
Add translations

### PR DESCRIPTION
**Pull request by UuuNyaa**
Translate untranslated terms

### CODE REVIEW

**Comment by powroupi** [comment]
Thanks for the changes. I'll merge it. :smile:

**Comment by nagadomi** [comment]
`Add Joint` popup dialog (`View3D > Sidebar > MMD > Joint > +`) also has some untranslated terms.

**Comment by powroupi** [comment]
@nagadomi , currently we don't translate descriptions, so that's expected. :smile: 

EDIT:
It seems this method does not work for descriptions, so we have to use other way to translate them. :cry:

**Comment by nagadomi** [comment]
@powroupi 
If it refers to descriptions on tooltip, then check `Preferences > Interface > Translation > Tooltips` and they will be translated.

**Pull request merged**
