### PR TITLE
fix for non-windows paths and including toon textures

### PR DESCRIPTION
**Pull request by ptrthomas**
I notice you are actively working on this, and would like to help.  Do send me a message on github and we can connect over e-mail.  Let me know if you have any specific problems you are trying to solve and need help on.

Regarding this pull request, you may need only the last 2 commits.  If you are interested, I was able to set up a way to debug the addon code in PyDev.  I am able to have everything work on a Mac.

### CODE REVIEW

**Comment by powroupi** [comment]
Thank you for your changes!

About this branch, i did a lot custom changes for my use cases, some are experimental
so it may not be merged into sugiany's master (it's sugiany's deal).

About the commit 9995627, it is good for importing but i guess we need to change back
to windows-based path when exporting, so that we don't get trouble to use the 
pmx file in cross-platform. Would you like to do this before i merge it ?

ps. Sorry for my english! And i would need your help for adding proper english descriptions in UI...

**Comment by ptrthomas** [comment]
You are right ! I just made https://github.com/powroupi/blender_mmd_tools/pull/1/commits/0b2560e6ed7f6f2eb1669acc76f90a4e493e018e like you mentioned.  I also fixed a crash if a texture is missing.

I am using your changes because I think textures are supported a lot more, thanks for your work.  There is no need to merge my changes unless you think they are good.

Your english is great :)  I can certainly help.  I may take your help if I decide to translate the readme.md into english.

One question: I really don't understand all the physics and rigid body constraints magic that happens when importing into blender.  I am unable to add "normal" blender stuff onto a model.  My question is - do you think the current way of creating temp objects and joints is good or is there a better way in blender.  I am wondering whether it is worth rewriting how the rigid bodies and constraints are set up.

**Comment by powroupi** [comment]
Thanks for your changes. I would like to cherry-pick 9995627 & b1a269a.
About 0b2560e, I think it is better to setup manually so that we don't have the copies from MMD program.

I'm not good in japanese, so you may take a look at the forks of nakata0705 and pikangie if you decide to translate the readme.md. :)

In current workflow, you need to use the physics panels of mmd_tools to add rigid bodies and joints if you want to export model with physics. Otherwise, you should be able to use blender's physics tool to setup your physics as usual and forget the Build/Clean buttons.

The ncc objects is setup for collision mask settings which only avaiable in blender 2.77 game engine,
and the rigid track objects may be unnecessary if the rigidbody objects are well positioned.
I understand how they work but i can not explain well...sorry )(
I think there should be a better way to setup those physics but i don't have any idea for now.

For futher discussion, you may open an issue and let's discuss in there. :)

**Comment by ptrthomas** [comment]
> I would like to cherry-pick 9995627 & b1a269a.

Sounds great !

> About 0b2560e, I think it is better to setup manually so that we don't have the copies from MMD program.

Personally, since the files are so small, I thought it was ok.  Especially since I am on a Mac, it felt good that I can just install the addon and everything works right away.  Just my opinion, no worries :)

> I'm not good in japanese, so you may take a look at the forks of nakata0705 and pikangie if you decide to translate the readme.md. :)

Thanks for the pointer, I will explore those forks.

> Otherwise, you should be able to use blender's physics tool to setup your physics as usual and forget the Build/Clean buttons.

Somehow I get totally stuck here.  The moment I parent anything to "rigidbodies" it starts behaving strangely, I still need to understand all the joints / tracks.  In other words I am unable to mix existing mmd rigid bodies with new ones created using blender (and not the mmd_tools)

> The ncc objects is setup for collision mask settings which only avaiable in blender 2.77 game engine,
> I think there should be a better way to setup those physics but i don't have any idea for now.

Okay, that is useful information.

> For futher discussion, you may open an issue and let's discuss in there. :)

Yes, for the time being let me go through (and debug) the code in detail and figure out more about blender internals.  I will then come back to you with questions.

**Comment by powroupi** [comment]
I updated my branch and feel free to open issues if you have any questions, thank you!

**Pull request closed without merging**
