### PR TITLE
Avoid to raise exception on reload

### PR DESCRIPTION
**Pull request by SAM-tak**
mmd_tools occurs error on reloading and cannot be reloaded itself correctly.
This patch fix it.

### CODE REVIEW

**Comment by powroupi** [comment]
Sorry, I cannot reproduce the error, there is no error when I simply reload mmd_tools, any steps to reproduce the error? And base on your commit 38eb5b1, I'm afraid that a lot of files may need to do this kind of changes (I'm not sure :worried: ).

**Comment by SAM-tak** [comment]
Did you ever see those message in system console on reload(press F8)?

default

```
TypeError: PointerProperty(...) expected an RNA type, failed with: RuntimeError: , missing bl_rna attribute from 'RNAMetaPropGroup' instance (may not be registered)

Exception in module register(): 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\mmd_tools\\__init__.py'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 350, in enable
    mod.register()
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\mmd_tools\__init__.py", line 93, in register
    properties.register()
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\mmd_tools\properties\__init__.py", line 50, in register
    setattr(typ, attr, prop)
ValueError: bpy_struct "PoseBone" registration error: mmd_bone could not register
```
it occurred in my environment. There was a long time. When I modify mmd_tools,  I restart blender itself for test a modification instead of reloading (F8). I felt inconvenient for a long time, but sorry if you don't have a same problem.

**Comment by powroupi** [comment]
Well, I think that error only occur on reloading a modified mmd_tools. In my opinion, it might have more weird bugs if we just reload a modified mmd_tools instead of restarting Blender. Because some definitions may not be updated if we don't reload them properly, and I'm not sure if I understand [importlib.reload](https://docs.python.org/3/library/importlib.html#importlib.reload), sorry. :sweat: 

For example, do [these](https://github.com/powroupi/blender_mmd_tools/blob/6a26a07776199bd7b2187ae3405fb361d1ce988d/mmd_tools/core/pmx/importer.py#L11-L18)  definitions need to be reloaded if some of them are modified?

**Comment by powroupi** [comment]
Okay, I have updated my branch based on your commit 38eb5b1 without changing `mmd_tools/properties/root.py`. The issue should be fixed as well, you might double check it again, and you can close it if the issue is fixed. Thank you.  :smile: 

Sorry for losing your contributions, I'm not a git expert. Thank you for your changes. :sweat_smile:

**Comment by SAM-tak** [comment]
I apologize for previous dirty pull request.
It was not necessary changing mmd_tools/properties/root.py certainly.
Your changeset works fine in my environment too!

**Pull request closed without merging**
